version: "2"
services:
  # reverse-proxy:
  #   image: nginx:latest
  #   container_name: reverse-proxy
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #     - ./certbot/conf:/etc/nginx/ssl:ro
  #     - ./certbot/data:/var/www/certbot:ro
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - data-server
  #     - front

  # certbot : 
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/var/www/certbot -d test-helper.com -d api.test-helper.com --email jmchoi1225@ajou.ac.kr --agree-tos --no-eff-email
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt:rw
  #     - ./certbot/logs:/var/log/letsencrypt:rw
  #     - ./certbot/data:/var/www/certbot:rw

  data-server:
    container_name: data-server
    build:
      context: backend/testhelper/
      dockerfile: Dockerfile
    image: data-server:latest
    environment :
      - AWS_PROFILE=test-helper
    ports:
      - 8081:8081
    
    environment:
      - AWS_PROFILE=test-helper
    volumes:
      - ~/.aws/:/root/.aws:ro
    
  front: 
    container_name: front
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true