version: "2"
services:
  data-server:
    container_name: data-server
    build:
      context: backend/testhelper/
      dockerfile: Dockerfile
    image: data-server:latest
    environment:
      - AWS_PROFILE=test-helper
      - ENV_PROFILE=prod
    ports:
      - 8081:8081
    volumes:
      - ~/.aws/:/root/.aws:ro

  front:
    container_name: front
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
